#ifndef DEBUG_OPTIONS_GLSL
#define DEBUG_OPTIONS_GLSL

#define DEBUG_ALBEDO 0
#define DEBUG_NORMAL 1
#define DEBUG_METALLIC 2
#define DEBUG_ROUGHNESS 3
#define DEBUG_AO 4
#define DEBUG_SHADOW 5
#define DEBUG_CSM_SPLIT 6
#define DEBUG_LIGHT_TILE 7

#endif